### PR TITLE
Initial step to support Rails 7.0.z

### PR DESCRIPTION
**Pull request by yahonda**
This pull request needs https://github.com/pingcap/rails/pull/6 merged first to run CI.

### CODE REVIEW

**Comment by yahonda** [comment]
https://github.com/pingcap/rails/pull/6 has been merged.

**Comment by yahonda** [comment]
@hooopo Do you have any idea why `tidb530` job is always failing to connect to TiDB? 

https://github.com/pingcap/activerecord-tidb-adapter/runs/5746649173?check_suite_focus=true#step:6:4

```ruby
/home/runner/work/activerecord-tidb-adapter/activerecord-tidb-adapter/vendor/bundle/ruby/2.7.0/bundler/gems/rails-8e88c0ecd838/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:51:in `rescue in new_client': There is an issue connecting with your hostname: 127.0.0.1. (ActiveRecord::DatabaseConnectionError)
```
Please advise.

**Comment by yahonda** [comment]
I'm thinking about pushing the commit https://github.com/pingcap/activerecord-tidb-adapter/pull/37/commits/2369f6faa0a496e123eee683bbd415b281e2a10d made at https://github.com/pingcap/activerecord-tidb-adapter/pull/37 this pull request to this branch.

**Comment by yahonda** [comment]
Testing against official versions of Docker images. Will see how it goes.

**Comment by yahonda** [comment]
Running CI against official versions of Docker images introduces more errors and/or failures than I expected. Revert this change and let #37 investigate them.

**Comment by hooopo** [comment]
> @hooopo Do you have any idea why `tidb530` job is always failing to connect to TiDB?
> 
> https://github.com/pingcap/activerecord-tidb-adapter/runs/5746649173?check_suite_focus=true#step:6:4
> 
> ```ruby
> /home/runner/work/activerecord-tidb-adapter/activerecord-tidb-adapter/vendor/bundle/ruby/2.7.0/bundler/gems/rails-8e88c0ecd838/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:51:in `rescue in new_client': There is an issue connecting with your hostname: 127.0.0.1. (ActiveRecord::DatabaseConnectionError)
> ```
> 
> Please advise.

It seems that only v5.3.0 has not been passed. It may be a problem with the docker image. I will try to rebuild the docker image later.

**Comment by yahonda** [comment]
> It may be a problem with the docker image. I will try to rebuild the docker image later.

Thanks!

**Comment by hooopo** [comment]
I found that 5.3 and 5.4 docker images have the same problem, we can merge this PR first, remove 5.3 from ci, and then solve the docker problem in the new PR

**Comment by yahonda** [comment]
Removed `tidb530` from GitHub Actions.

**Review by hooopo — APPROVED** [review]

**Pull request merged**
