### PR TITLE
Rails main branch version is now 7.1.0.alpha

### PR DESCRIPTION
**Pull request by yahonda**
Refer https://github.com/rails/rails/commit/83d85b22074f1986077791234f737e0e4faba03b
Related to #33

### CODE REVIEW

**Comment by yahonda** [comment]
This pull request needs https://github.com/pingcap/rails main branch need to merge the upstream https://github.com/rails/rails changes.

https://github.com/pingcap/activerecord-tidb-adapter/runs/4613505724?check_suite_focus=true#step:4:41

```
Revision 310d62a443b9157bb48d778f49ba236e18b06b63 does not exist in the
repository https://github.com/pingcap/rails.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory
'/home/runner/work/activerecord-tidb-adapter/activerecord-tidb-adapter/vendor/bundle/ruby/2.7.0/bundler/gems/rails-310d62a443b9'
```

**Comment by yahonda** [comment]
Pushed https://github.com/pingcap/activerecord-tidb-adapter/pull/35/commits/f3600e21d246186de45b579c979528bfd84ed2cf to see if https://github.com/pingcap/rails/pull/5 works.

**Comment by yahonda** [comment]
Disabled bundler cache by setting `bundler-cache: false` to see if these CI failures are resolved.
https://github.com/pingcap/activerecord-tidb-adapter/runs/5671905045?check_suite_focus=true#step:4:21

This pull request just updates Gemfile.lock without changing Gemfile so I assume disabling bundler cache may help.

**Comment by hooopo** [comment]
By the way, we can use the official docker image and see if it will be more stable https://hub.docker.com/r/pingcap/tidb/tags

**Comment by yahonda** [comment]
Once this pull request becomes green I'll open another pull request to use the official docker image. Thanks for the info.

**Comment by yahonda** [comment]
I'm investigating CI failures.

**Comment by yahonda** [comment]
Looks like some Rails change needs savepoint support. Let me work for #36 first to support Rails 7.0.z then will tackle Rails 7.1.z support.

**Comment by yahonda** [comment]
Closing this pull request for now because it has some conflicts to support Rails 7.0.z first. Let me open another pull request once Active Record TiDB Adapter 7.0.z is released.

**Pull request closed without merging**
